/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface KuoAvatar {}
  interface KuoAvatarAttributes extends StencilHTMLAttributes {}

  interface KuoExample {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface KuoExampleAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface KuoMain {}
  interface KuoMainAttributes extends StencilHTMLAttributes {}

  interface KuoRecipes {}
  interface KuoRecipesAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'KuoAvatar': Components.KuoAvatar;
    'KuoExample': Components.KuoExample;
    'KuoMain': Components.KuoMain;
    'KuoRecipes': Components.KuoRecipes;
  }

  interface StencilIntrinsicElements {
    'kuo-avatar': Components.KuoAvatarAttributes;
    'kuo-example': Components.KuoExampleAttributes;
    'kuo-main': Components.KuoMainAttributes;
    'kuo-recipes': Components.KuoRecipesAttributes;
  }


  interface HTMLKuoAvatarElement extends Components.KuoAvatar, HTMLStencilElement {}
  var HTMLKuoAvatarElement: {
    prototype: HTMLKuoAvatarElement;
    new (): HTMLKuoAvatarElement;
  };

  interface HTMLKuoExampleElement extends Components.KuoExample, HTMLStencilElement {}
  var HTMLKuoExampleElement: {
    prototype: HTMLKuoExampleElement;
    new (): HTMLKuoExampleElement;
  };

  interface HTMLKuoMainElement extends Components.KuoMain, HTMLStencilElement {}
  var HTMLKuoMainElement: {
    prototype: HTMLKuoMainElement;
    new (): HTMLKuoMainElement;
  };

  interface HTMLKuoRecipesElement extends Components.KuoRecipes, HTMLStencilElement {}
  var HTMLKuoRecipesElement: {
    prototype: HTMLKuoRecipesElement;
    new (): HTMLKuoRecipesElement;
  };

  interface HTMLElementTagNameMap {
    'kuo-avatar': HTMLKuoAvatarElement
    'kuo-example': HTMLKuoExampleElement
    'kuo-main': HTMLKuoMainElement
    'kuo-recipes': HTMLKuoRecipesElement
  }

  interface ElementTagNameMap {
    'kuo-avatar': HTMLKuoAvatarElement;
    'kuo-example': HTMLKuoExampleElement;
    'kuo-main': HTMLKuoMainElement;
    'kuo-recipes': HTMLKuoRecipesElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
