/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface KuoAvatar {
    'speech': string;
  }
  interface KuoAvatarAttributes extends StencilHTMLAttributes {
    'speech'?: string;
  }

  interface KuoMain {}
  interface KuoMainAttributes extends StencilHTMLAttributes {}

  interface KuoRecipes {
    'recipes': any[];
  }
  interface KuoRecipesAttributes extends StencilHTMLAttributes {
    'recipes'?: any[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'KuoAvatar': Components.KuoAvatar;
    'KuoMain': Components.KuoMain;
    'KuoRecipes': Components.KuoRecipes;
  }

  interface StencilIntrinsicElements {
    'kuo-avatar': Components.KuoAvatarAttributes;
    'kuo-main': Components.KuoMainAttributes;
    'kuo-recipes': Components.KuoRecipesAttributes;
  }


  interface HTMLKuoAvatarElement extends Components.KuoAvatar, HTMLStencilElement {}
  var HTMLKuoAvatarElement: {
    prototype: HTMLKuoAvatarElement;
    new (): HTMLKuoAvatarElement;
  };

  interface HTMLKuoMainElement extends Components.KuoMain, HTMLStencilElement {}
  var HTMLKuoMainElement: {
    prototype: HTMLKuoMainElement;
    new (): HTMLKuoMainElement;
  };

  interface HTMLKuoRecipesElement extends Components.KuoRecipes, HTMLStencilElement {}
  var HTMLKuoRecipesElement: {
    prototype: HTMLKuoRecipesElement;
    new (): HTMLKuoRecipesElement;
  };

  interface HTMLElementTagNameMap {
    'kuo-avatar': HTMLKuoAvatarElement
    'kuo-main': HTMLKuoMainElement
    'kuo-recipes': HTMLKuoRecipesElement
  }

  interface ElementTagNameMap {
    'kuo-avatar': HTMLKuoAvatarElement;
    'kuo-main': HTMLKuoMainElement;
    'kuo-recipes': HTMLKuoRecipesElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
